version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379' 
    command: ["redis-server"] 
    volumes:
      - redis_data:/data  

  app:
    build: .
    ports:
      - '3002:3002'  
    env_file:
      - .env  
    volumes:
      - .:/app 
    depends_on:
      - redis 

volumes:
  redis_data:  
